import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790450162532 implements MigrationInterface {
    name = 'InitialSchema1790450162532'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "full_name" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'admin', "phone" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "testimonials" ("id" SERIAL NOT NULL, "client_name" character varying NOT NULL, "client_city" character varying, "rating" integer NOT NULL, "comment" text NOT NULL, "project_type" character varying, "published" boolean NOT NULL DEFAULT true, "featured" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_63b03c608bd258f115a0a4a1060" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "site_image_overrides" ("key" character varying(60) NOT NULL, "url" character varying(500) NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_01e4ac261d03e9714780a2d71f9" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "quote_requests" ("id" SERIAL NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "project_type" character varying, "message" text NOT NULL, "status" character varying NOT NULL DEFAULT 'nouveau', "surface_area" character varying, "rooms" character varying, "current_state" character varying, "desired_timeline" character varying, "budget_range" character varying, "utm_source" character varying, "utm_medium" character varying, "utm_campaign" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c05f72de8be0ec6b0985a851558" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_documents" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "name" character varying NOT NULL, "file_url" character varying NOT NULL, "document_type" character varying NOT NULL, "uploaded_by_role" character varying NOT NULL DEFAULT 'admin', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c0d7fa982569e84a809aa2ff5d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_updates" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "title" character varying NOT NULL, "message" text, "is_visible_to_client" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2093d4d18851bc0f6ec8b1197e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" SERIAL NOT NULL, "reference_number" character varying NOT NULL, "client_id" integer NOT NULL, "quote_request_id" integer, "title" character varying NOT NULL, "description" text, "status" character varying NOT NULL DEFAULT 'devis_en_cours', "total_amount" numeric(10,2), "deposit_amount" numeric(10,2), "deposit_percentage" integer NOT NULL DEFAULT '30', "estimated_start_date" date, "estimated_end_date" date, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_72469f34171d60ba0f7506feab4" UNIQUE ("reference_number"), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "price_references" ("id" SERIAL NOT NULL, "category" character varying NOT NULL, "work_item" character varying NOT NULL, "label" character varying NOT NULL, "unit" character varying NOT NULL DEFAULT 'm2', "price_low" numeric(10,2) NOT NULL, "price_mid" numeric(10,2) NOT NULL, "price_high" numeric(10,2) NOT NULL, "active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4d5894be9c1698cedc15dcfedcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "portfolio" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text, "image_url" character varying NOT NULL, "category" character varying, "published" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6936bb92ca4b7cda0ff28794e48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "stripe_session_id" character varying, "stripe_payment_intent_id" character varying, "amount" numeric(10,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "payment_type" character varying NOT NULL, "description" character varying, "receipt_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "newsletter_subscribers" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "subscribed_at" TIMESTAMP NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "unsubscribe_token" uuid NOT NULL DEFAULT gen_random_uuid(), "unsubscribed_at" TIMESTAMP, CONSTRAINT "UQ_0dc48416511f011f7de7b2a8f83" UNIQUE ("email"), CONSTRAINT "UQ_82a83e8cdd1c7e0774e486f857a" UNIQUE ("unsubscribe_token"), CONSTRAINT "PK_38f9333e9961b2fdb589128d19b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "estimations" ("id" SERIAL NOT NULL, "session_id" character varying NOT NULL, "category" character varying NOT NULL, "surface_area" numeric(10,2) NOT NULL, "rooms" integer, "quality_level" character varying NOT NULL DEFAULT 'standard', "selected_items" jsonb NOT NULL, "total_low" numeric(10,2) NOT NULL, "total_mid" numeric(10,2) NOT NULL, "total_high" numeric(10,2) NOT NULL, "first_name" character varying, "last_name" character varying, "email" character varying, "phone" character varying, "converted_to_quote" boolean NOT NULL DEFAULT false, "utm_source" character varying, "utm_medium" character varying, "utm_campaign" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c7ec983ab9a4dccf21b74198cd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blog_posts" ("id" SERIAL NOT NULL, "title" character varying(200) NOT NULL, "slug" character varying NOT NULL, "excerpt" text, "content" text NOT NULL, "cover_image_url" character varying, "category" character varying, "tags" text, "author" character varying NOT NULL DEFAULT 'Atouts Services', "published" boolean NOT NULL DEFAULT false, "published_at" TIMESTAMP, "meta_title" character varying, "meta_description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5b2818a2c45c3edb9991b1c7a51" UNIQUE ("slug"), CONSTRAINT "PK_dd2add25eac93daefc93da9d387" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "city_pages" ("id" SERIAL NOT NULL, "slug" character varying NOT NULL, "city_name" character varying NOT NULL, "department" character varying, "postal_code" character varying, "content" text NOT NULL, "hero_image_url" character varying, "meta_title" character varying, "meta_description" text, "published" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_20b34a4ac0f8f0673e3b559abf5" UNIQUE ("slug"), CONSTRAINT "PK_5309cfd2fd9c2fb983f87bd71c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "before_after" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text, "before_image_url" character varying NOT NULL, "after_image_url" character varying NOT NULL, "category" character varying NOT NULL, "published" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0031dfac7b256029ae222861dee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "site_events" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(40) NOT NULL, "path" character varying(300) NOT NULL, "props" jsonb NOT NULL DEFAULT '{}', "source" character varying(100) NOT NULL, "utm_campaign" character varying(150), "city" character varying(100), "device" character varying(10) NOT NULL, "visitor" character varying(16) NOT NULL, CONSTRAINT "PK_a7ff845643777c7b38a1f015127" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f3048239f1b1a05d6002f2a8a" ON "site_events" ("created_at", "name") `);
        await queryRunner.query(`CREATE TABLE "page_views" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "path" character varying(300) NOT NULL, "source" character varying(100) NOT NULL, "referrer_host" character varying(200), "utm_source" character varying(100), "utm_medium" character varying(100), "utm_campaign" character varying(150), "country" character varying(2), "city" character varying(100), "device" character varying(10) NOT NULL, "visitor" character varying(16) NOT NULL, CONSTRAINT "PK_3b1047277a9c2a8cfd618787671" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db58d558e3874d39209a06bd3c" ON "page_views" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "project_documents" ADD CONSTRAINT "FK_ce91a721e078a2d9852b61ad8f2" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_updates" ADD CONSTRAINT "FK_80cfd62a1d7c871fa100645f427" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_ca29f959102228649e714827478" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_7fdb872b62fe37d76cdb5a11147" FOREIGN KEY ("quote_request_id") REFERENCES "quote_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_7679cab4a6968de68c2a1a8faf2" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_7679cab4a6968de68c2a1a8faf2"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_7fdb872b62fe37d76cdb5a11147"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_ca29f959102228649e714827478"`);
        await queryRunner.query(`ALTER TABLE "project_updates" DROP CONSTRAINT "FK_80cfd62a1d7c871fa100645f427"`);
        await queryRunner.query(`ALTER TABLE "project_documents" DROP CONSTRAINT "FK_ce91a721e078a2d9852b61ad8f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db58d558e3874d39209a06bd3c"`);
        await queryRunner.query(`DROP TABLE "page_views"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f3048239f1b1a05d6002f2a8a"`);
        await queryRunner.query(`DROP TABLE "site_events"`);
        await queryRunner.query(`DROP TABLE "before_after"`);
        await queryRunner.query(`DROP TABLE "city_pages"`);
        await queryRunner.query(`DROP TABLE "blog_posts"`);
        await queryRunner.query(`DROP TABLE "estimations"`);
        await queryRunner.query(`DROP TABLE "newsletter_subscribers"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TABLE "portfolio"`);
        await queryRunner.query(`DROP TABLE "price_references"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "project_updates"`);
        await queryRunner.query(`DROP TABLE "project_documents"`);
        await queryRunner.query(`DROP TABLE "quote_requests"`);
        await queryRunner.query(`DROP TABLE "site_image_overrides"`);
        await queryRunner.query(`DROP TABLE "testimonials"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
